CREATE PROC FI_SP_AltBeneficiario
	@Id	INT,
    @NOME			VARCHAR (50) ,
	@CPF			VARCHAR (11),
	@IDCLIENTE				INT
AS
BEGIN
	UPDATE BENEFICIARIOS 
	SET 
		    @NOME		= @NOME,
			@CPF		= @CPF,
			@IDCLIENTE	= @IDCLIENTE
	WHERE Id = @Id
END