CREATE PROC FI_SP_PesquisaBeneficiario
	@ID		BIGINT = NULL,
	@NOME   VARCHAR(50) = NULL
AS
BEGIN
	SELECT ID, NOME, CPF, IDCLIENTE 
	FROM BENEFICIARIOS WITH(NOLOCK)
	WHERE ((ID = @ID) OR (@ID IS NULL)) AND
		((NOME like '%' + @nome + '%') OR (@NOME IS NULL))
END